var i = 0;
function allowDrop(ev) {
    ev.preventDefault();
}
function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
} function drop(ev) {
    ev.preventDefault();
var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}
function rollability(){             
    var statroll1 = Math.floor(Math.random()*6)+1;
    var statroll2 = Math.floor(Math.random()*6)+1;
    var statroll3 = Math.floor(Math.random()*6)+1;
    var statroll4 = Math.floor(Math.random()*6)+1; 
    var totalroll = [statroll1,statroll2,statroll3,statroll4];
    var finalroll = statroll1 + ", " + statroll2 + ", " + statroll3 + ", " +statroll4;  
    var min = Math.min(...totalroll);
        document.getElementById("statroll").innerHTML = finalroll
        document.getElementById("minroll").innerHTML = min  
    if (i===0){
        document.getElementById("stattotal1").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;
    }else if (i===1){
        document.getElementById("stattotal2").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;               
    }else if (i===2){
        document.getElementById("stattotal3").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;    
    }else if (i===3) {
        document.getElementById("stattotal4").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;     
    }else if (i===4) {
        document.getElementById("stattotal5").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;     
    }else if (i===5) {
        document.getElementById("stattotal6").innerHTML = +statroll1 + +statroll2 + +statroll3 + +statroll4 - +min
        i++;     
    }else {
        document.getElementById("overroll").innerHTML =  "You have reached your limit on rolls. Please allocate the previous 6 rolls to the desired stats."  
    }
};   
function raceinput(){
var race = document.getElementById("raceselect").value; 
    document.getElementById("yourrace").innerHTML = "You selected: " + race;
};
function classinput(){
var classes = document.getElementById("classselect").value; 
    document.getElementById("yourclass").innerHTML = "Because you chose " + classes + " ,You get the following options for equipment:";
if (classes === "Barbarian") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="hidden"
    document.getElementById("optiond").style.visibility="hidden"
    document.getElementById("optione").style.visibility="hidden"
    document.getElementById("aa").innerHTML = "A greataxe"
    document.getElementById("ab").innerHTML = "Any martial melee weapon"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"
    document.getElementById("ba").innerHTML = "Two Handaxes"
    document.getElementById("bb").innerHTML = "Any simple weapon"
}else if (classes === "Bard") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden"
    document.getElementById("optione").style.visibility="hidden"
    document.getElementById("aa").innerHTML = "A rapier"
    document.getElementById("ab").innerHTML = "A longsword"
    document.getElementById("acr").style.visibility = "visible"
    document.getElementById("ac").style.visibility = "visible"
    document.getElementById("ac").innerHTML = "Any simple weapon"   
    document.getElementById("ba").innerHTML = "A diplomat's pack"
    document.getElementById("bb").innerHTML = "An entertainer's pack"
    document.getElementById("ca").innerHTML = "A lute"
    document.getElementById("cb").innerHTML = "Any other musical instrument"
}else if (classes === "Cleric") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="visible"
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "Scale mail"
    document.getElementById("ab").innerHTML = "Leather armour"
    document.getElementById("acr").style.visibility = "visible"
    document.getElementById("ac").style.visibility = "visible"    
    document.getElementById("ac").innerHTML = "Chain mail (if prof.)"   
    document.getElementById("ba").innerHTML = "A mace"
    document.getElementById("bb").innerHTML = "A warhammer (if prof.)"
    document.getElementById("ca").innerHTML = "A light crossbow and 20 bolts"
    document.getElementById("cb").innerHTML = "Any simple weapon" 
    document.getElementById("da").innerHTML = "A priest's pack"
    document.getElementById("db").innerHTML = "An explorer's pack" 
    document.getElementById("ea").innerHTML = "A shield and a holy symbol"
}else if (classes === "Druid") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="hidden"
    document.getElementById("optiond").style.visibility="hidden"
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "A wooden shield"
    document.getElementById("ab").innerHTML = "Any simple weapon"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A scimitar"
    document.getElementById("bb").innerHTML = "Any simple melee weapon"
    document.getElementById("ea").innerHTML = "Leather armour, an explorer's pack, and a Druid focus"
}else if (classes === "Fighter") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="visible"
    document.getElementById("optione").style.visibility="hidden"
    document.getElementById("aa").innerHTML = "Chain mail"
    document.getElementById("ab").innerHTML = "Leather armour, a longbow, and 20 arrows"
    document.getElementById("acr").style.visibility = "hidden" 
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A martial weapon and a shield"
    document.getElementById("bb").innerHTML = "two martial weapons"
    document.getElementById("ca").innerHTML = "A light crossbow and 20 bolts"
    document.getElementById("cb").innerHTML = "Two handaxes" 
    document.getElementById("da").innerHTML = "A dungeoneer's pack"
    document.getElementById("db").innerHTML = "An explorer's pack" 
} else if (classes === "Monk") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="hidden"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"    
    document.getElementById("aa").innerHTML = "A shortsword"
    document.getElementById("ab").innerHTML = "Any simple weapon"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A dungeoneer's pack"
    document.getElementById("bb").innerHTML = "An explorer's pack"
    document.getElementById("ea").innerHTML = "10 darts"
} else if (classes === "Paladin") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"  
    document.getElementById("aa").innerHTML = "A martial weapon and a shield"
    document.getElementById("ab").innerHTML = "two martial weapons"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "Five javelins"
    document.getElementById("bb").innerHTML = "Any simple melee weapon"
    document.getElementById("ca").innerHTML = "A priest's pack"
    document.getElementById("cb").innerHTML = "An explorer's pack"  
    document.getElementById("ea").innerHTML = "Chain mail and a holy symbol"    
} else if (classes === "Ranger") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "Scale mail"
    document.getElementById("ab").innerHTML = "Leather armour"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "Two shortswords"
    document.getElementById("bb").innerHTML = "Two simple melee weapons"
    document.getElementById("ca").innerHTML = "A dungeoneer's pack"
    document.getElementById("cb").innerHTML = "An explorer's pack"  
    document.getElementById("ea").innerHTML = "A longbow and a quiver of 20 arrows"    
} else if (classes === "Rogue") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "A burglar's pack"
    document.getElementById("ab").innerHTML = "A dungeoneer's pack"
    document.getElementById("acr").style.visibility = "visible"
    document.getElementById("ac").style.visibility = "visible"    
    document.getElementById("ac").innerHTML = "An explorer's pack"    
    document.getElementById("ba").innerHTML = "A rapier"
    document.getElementById("bb").innerHTML = "A shortsword"
    document.getElementById("ca").innerHTML = "A shortsword"
    document.getElementById("cb").innerHTML = "A shortbow and quiver of 20 arrows"  
    document.getElementById("ea").innerHTML = "Leater armour, two daggers, and thieves tools"     
} else if (classes === "Sorcerer") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "A light crossbow and 20 bolts"
    document.getElementById("ab").innerHTML = "Any simple weapon"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A component pouch"
    document.getElementById("bb").innerHTML = "An arcane focus"
    document.getElementById("ca").innerHTML = "A dungeoneer's pack"
    document.getElementById("cb").innerHTML = "An explorer's pack"  
    document.getElementById("ea").innerHTML = "Two daggers"
} else if (classes === "Warlock") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "A light crossbow and 20 bolts"
    document.getElementById("ab").innerHTML = "Any simple weapon"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A component pouch"
    document.getElementById("bb").innerHTML = "An arcane focus"
    document.getElementById("ca").innerHTML = "A scholar's pack"
    document.getElementById("cb").innerHTML = "A dungeoneer's pack"  
    document.getElementById("ea").innerHTML = "Leather armour, any simple weapon, and two daggers"
} else if (classes === "Wizard") {
    document.getElementById("optiona").style.visibility="visible"
    document.getElementById("optionb").style.visibility="visible"
    document.getElementById("optionc").style.visibility="visible"
    document.getElementById("optiond").style.visibility="hidden" 
    document.getElementById("optione").style.visibility="visible"
    document.getElementById("aa").innerHTML = "A quarterstaff"
    document.getElementById("ab").innerHTML = "A dagger"
    document.getElementById("acr").style.visibility = "hidden"
    document.getElementById("ac").style.visibility = "hidden"    
    document.getElementById("ba").innerHTML = "A component pouch"
    document.getElementById("bb").innerHTML = "An arcane focus"
    document.getElementById("ca").innerHTML = "A scholar's pack"
    document.getElementById("cb").innerHTML = "An explorer's pack"  
    document.getElementById("ea").innerHTML = "A spellbook"
    }
                
};
              function backgroundinput(){
                var background = document.getElementById("backgroundselect").value; 
                if (background === "Acolyte") {  
                document.getElementById("bonus6").style.visibility="visible";
                document.getElementById("bonus8").style.visibility="hidden";
                document.getElementById("bonus10").style.visibility="hidden";
                document.getElementById("bonus20").style.visibility="hidden";    
                document.getElementById("p1").innerHTML = "I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example."
                document.getElementById("p2").innerHTML = "I can find commo ground between the fiercest enemies, empathizing with them and always working towards peace."
                document.getElementById("p3").innerHTML = "I see omens in every event and action. The gods try to speak to us, we just need to listen"
                document.getElementById("p4").innerHTML = "Nothing can shake my optimistic attitude."
                document.getElementById("p5").innerHTML = "I quote (or misquote) sacred texts and proverbs in almost every situation."
                document.getElementById("p6").innerHTML = "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods."
                document.getElementById("p7").innerHTML = "I've enjoyed fine food, drink, and high society among my temple’s elite. Rough living grates on me."
                document.getElementById("p8").innerHTML = "I’ve spent so long in the temple that I have little practical experience dealing with people in the outside world."
                document.getElementById("i1").innerHTML = "Tradition. The ancient traditions o f worship and sacrifice must be preserved and upheld. (Lawful)"
                document.getElementById("i2").innerHTML = "Charity. I always try to help those in need, no matter what the personal cost. (Good)"
                document.getElementById("i3").innerHTML = "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)"
                document.getElementById("i4").innerHTML = "Power. I hope to one day rise to the top of my faith’s religious hierarchy. (Lawful)"
                document.getElementById("i5").innerHTML = "Faith. I trust that my deity will guide my actions, I have faith that if I work hard, things will go well. (Lawful)"
                document.getElementById("i6").innerHTML = "Aspiration. I seek to prove myself worthy of my god’s favor by matching my actions against his or her teachings. (Any)"
                document.getElementById("b1").innerHTML = "I would die to recover an ancient relic of my faith that was lost long ago."
                document.getElementById("b2").innerHTML = "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic."
                document.getElementById("b3").innerHTML = "I owe my life to the priest who took me in when my parents died."
                document.getElementById("b4").innerHTML = "Everything I do is for the common people."
                document.getElementById("b5").innerHTML = "I will do anything to protect the temple where I served."
                document.getElementById("b6").innerHTML = "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy."
                document.getElementById("f1").innerHTML = "I judge others harshly, and myself even more severely."
                document.getElementById("f2").innerHTML = "I put too much trust in those who wield power within my temple’s hierarchy."
                document.getElementById("f3").innerHTML = "My piety sometimes leads me to blindly trust those that profess faith in my god."
                document.getElementById("f4").innerHTML = "I am inflexible in my thinking."
                document.getElementById("f5").innerHTML = "I am suspicious of strangers and expect the worst of them."
                document.getElementById("f6").innerHTML = "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."  
                }else if (background ==="Charlatan") {
                    document.getElementById("bonus6").style.visibility="visible";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I fall in and out of love easily, and am always pursuing someone.";
                    document.getElementById("p2").innerHTML = "I have a joke for every occasion, especially occasions where humor is inappropriate.";
                    document.getElementById("p3").innerHTML = "Flattery is my preferred trick for getting what I want.";
                    document.getElementById("p4").innerHTML = "I’m a born gambler who can't resist taking a risk for a potential payoff.";
                    document.getElementById("p5").innerHTML = "I lie about almost everything, even when there’s no good reason to.";
                    document.getElementById("p6").innerHTML = "Sarcasm and insults are my weapons of choice.";
                    document.getElementById("p7").innerHTML = "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.";
                    document.getElementById("p8").innerHTML = "I pocket anything I see that might have some value.";
                    document.getElementById("i1").innerHTML = "Independence. I am a free spirit— no one tells me what to do. (Chaotic)";
                    document.getElementById("i2").innerHTML = "Fairness. I never target people who can’t afford to lose a few coins. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Charity. I distribute the money I acquire to the people who really need it. (Good)";
                    document.getElementById("i4").innerHTML = "Creativity. I never run the same con twice. (Chaotic)";   
                    document.getElementById("i5").innerHTML = "Friendship. Material goods come and go. Bonds of friendship last forever. (Good)";  
                    document.getElementById("i6").innerHTML = "Aspiration. I’m determined to make something of myself. (Any)"; 
                    document.getElementById("b1").innerHTML = "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.";
                    document.getElementById("b2").innerHTML = "I owe everything to my mentor—a horrible person who’s probably rotting in jail somewhere.";
                    document.getElementById("b3").innerHTML = "Somewhere out there, I have a child who doesn’t know me. I’m making the world better for him or her.";
                    document.getElementById("b4").innerHTML = "I come from a noble family, and one day I’ll reclaim my lands and title from those who stole them from me.";
                    document.getElementById("b5").innerHTML = "A powerful person killed someone I love. Some day soon, I’ll have my revenge.";
                    document.getElementById("b6").innerHTML = "I swindled and ruined a person who didn’t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.";
                    document.getElementById("f1").innerHTML = "I can’t resist a pretty face.";
                    document.getElementById("f2").innerHTML = "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in..";
                    document.getElementById("f3").innerHTML = "I’m convinced that no one could ever fool me the way I fool others.";
                    document.getElementById("f4").innerHTML = "I’m too greedy for my own good. I can’t resist taking a risk if there’s money involved.";
                    document.getElementById("f5").innerHTML = "I can’t resist swindling people who are more powerful than me.";
                    document.getElementById("f6").innerHTML = "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough."; 
                    document.getElementById("60").innerHTML = "Select a Scam";
                    document.getElementById("61").innerHTML = "I cheat at games of chance.";
                    document.getElementById("62").innerHTML = "I shave coins or forge documents.";
                    document.getElementById("63").innerHTML = "I insinuate myself into people’s lives to prey on their weakness and secure their fortunes.";
                    document.getElementById("64").innerHTML = "I put on new identities like clothes.";
                    document.getElementById("65").innerHTML = "I run sleight-of-hand cons on street corners.";
                    document.getElementById("66").innerHTML = "I convince people that worthless junk is worth their hard-earned money.";
                }else if (background === "Criminal") {   
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="visible";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I always have a plan for what to do when things go wrong.";
                    document.getElementById("p2").innerHTML = "I am always calm, no matter what the situation. I neevr raise my voice or let me emotions control me.";
                    document.getElementById("p3").innerHTML = "The first thing I do in a new location is note the locations of everything valuable- or where such things could be hidden.";
                    document.getElementById("p4").innerHTML = "I would rather make a new friend than a new enemy.";
                    document.getElementById("p5").innerHTML = "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.";
                    document.getElementById("p6").innerHTML = "I don't pay attention to the risks of a situation. Never tell me the odds.";
                    document.getElementById("p7").innerHTML = "The best way to get me to do something is to tell me I can't do it.";
                    document.getElementById("p8").innerHTML = "I blow up at the slightest insult.";
                    document.getElementById("i1").innerHTML = "Honor. I don’t steal from others in the trade. (Lawful)";
                    document.getElementById("i2").innerHTML = "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)";    
                    document.getElementById("i3").innerHTML = "Charity. I steal from the wealthy so that I can help people in need. (Good)";
                    document.getElementById("i4").innerHTML = "Greed. I will do whatever it takes to become wealthy. (Evil)";   
                    document.getElementById("i5").innerHTML = "People. I’m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Redemption. There’s a spark of good in everyone. (Good)"; 
                    document.getElementById("b1").innerHTML = "I’m trying to pay off an old debt I owe to a generous benefactor.";
                    document.getElementById("b2").innerHTML = "My ill-gotten gains go to support my family.";
                    document.getElementById("b3").innerHTML = "Something important was taken from me, and I aim to steal it back.";
                    document.getElementById("b4").innerHTML = "I will become the greatest thief that ever lived.";
                    document.getElementById("b5").innerHTML = "I’m guilty of a terrible crime. I hope I can redeem myself for it.";
                    document.getElementById("b6").innerHTML = "Someone I loved died because of a mistake I made. That will never happen again.";
                    document.getElementById("f1").innerHTML = "When I see something valuable, I can’t think about anything but how to steal it.";
                    document.getElementById("f2").innerHTML = "When faced with a choice between money and my friends, I usually choose the money.";
                    document.getElementById("f3").innerHTML = "If there’s a plan, I’ll forget it. If I don’t forget it, I’ll ignore it.";
                    document.getElementById("f4").innerHTML = "I have a “tell” that reveals when I'm lying.";
                    document.getElementById("f5").innerHTML = "I turn tail and run when things look bad.";
                    document.getElementById("f6").innerHTML = "An innocent person is in prison for a crime that I committed. I’m okay with that.";
                    document.getElementById("80").innerHTML = "Choose a Specialty";
                    document.getElementById("81").innerHTML = "Blackmailer";
                    document.getElementById("82").innerHTML = "Burglar";
                    document.getElementById("83").innerHTML = "Enforcer";
                    document.getElementById("84").innerHTML = "Fence";
                    document.getElementById("85").innerHTML = "Highway robber";
                    document.getElementById("86").innerHTML = "Hired killer";
                    document.getElementById("87").innerHTML = "Pickpocket";
                    document.getElementById("88").innerHTML = "Smuggler";                  
                    }else if (background === "Entertainer") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="visible";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I know a story relevant to almost every situation.";
                    document.getElementById("p2").innerHTML = "Whenever I come to a new place, I collect local rumors and spread gossip.";
                    document.getElementById("p3").innerHTML = "I’m a hopeless romantic, always searching for that “special someone.”";
                    document.getElementById("p4").innerHTML = "Nobody stays angry at me or around me for long, since I can defuse any amount of tension.";
                    document.getElementById("p5").innerHTML = "I love a good insult, even one directed at me.";
                    document.getElementById("p6").innerHTML = "I get bitter if I’m not the center of attention.";
                    document.getElementById("p7").innerHTML = "I’ll settle for nothing less than perfection.";
                    document.getElementById("p8").innerHTML = "I change my mood or my mind as quickly as I change key in a song.";
                    document.getElementById("i1").innerHTML = "Beauty. When I perform, I make the world better than it was. (Good)";
                    document.getElementById("i2").innerHTML = "Tradition. The stories, legends, and songs of the past must never be forgotten, for they teach us who we are. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Creativity. The world is in need of new ideas and bold action. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Greed. I’m only in it for the money and fame. (Evil)";   
                    document.getElementById("i5").innerHTML = "People. I like seeing the smiles on people’s faces when I perform. That’s all that matters. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)"; 
                    document.getElementById("b1").innerHTML = "My instrument is my most treasured possession, and it reminds me of someone I love.";
                    document.getElementById("b2").innerHTML = "Someone stole my precious instrument, and someday I’ll get it back.";
                    document.getElementById("b3").innerHTML = "I want to be famous, whatever it takes.";
                    document.getElementById("b4").innerHTML = "I idolize a hero of the old tales and measure my deeds against that person’s.";
                    document.getElementById("b5").innerHTML = "I will do anything to prove myself superior to my hated rival.";
                    document.getElementById("b6").innerHTML = "I would do anything for the other members of my old troupe.";
                    document.getElementById("f1").innerHTML = "I’ll do anything to win fame and renown.";
                    document.getElementById("f2").innerHTML = "I’m a sucker for a pretty face.";
                    document.getElementById("f3").innerHTML = "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.";
                    document.getElementById("f4").innerHTML = "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.";
                    document.getElementById("f5").innerHTML = "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.";
                    document.getElementById("f6").innerHTML = "Despite my best efforts, I am unreliable to my friends."; 
                    document.getElementById("100").innerHTML = "Select an Entertainer Routine.";
                    document.getElementById("101").innerHTML = "Actor";
                    document.getElementById("102").innerHTML = "Dancer";
                    document.getElementById("103").innerHTML = "Fire-eater";
                    document.getElementById("104").innerHTML = "Jester";
                    document.getElementById("105").innerHTML = "juggler";
                    document.getElementById("106").innerHTML = "Instrumentalist";
                    document.getElementById("107").innerHTML = "Poet";
                    document.getElementById("108").innerHTML = "Singer";
                    document.getElementById("109").innerHTML = "Storyteller";
                    document.getElementById("1010").innerHTML = "Tumbler";    
                    }else if (background === "Folk Hero") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="visible";
                    document.getElementById("bonus20").style.visibility="hidden";    
                    document.getElementById("p1").innerHTML = "I judge people by their actions, not their words.";
                    document.getElementById("p2").innerHTML = "If someone is in trouble, I’m always ready to lend help.";
                    document.getElementById("p3").innerHTML = "When I set my mind to something, I follow through no matter what gets in my way.";
                    document.getElementById("p4").innerHTML = "I have a strong sense of fair play and always try to find the most equitable solution to arguments.";
                    document.getElementById("p5").innerHTML = "I’m confident in my own abilities and do what I can to instill confidence in others.";
                    document.getElementById("p6").innerHTML = "Thinking is for other people. I prefer action.";
                    document.getElementById("p7").innerHTML = "I misuse long words in an attempt to sound smarter.";
                    document.getElementById("p8").innerHTML = "I get bored easily. When am I going to get on with my destiny?";
                    document.getElementById("i1").innerHTML = "Respect. People deserve to be treated with dignity and respect. (Good)";
                    document.getElementById("i2").innerHTML = "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Might. If I become strong, I can take what I want— what I deserve. (Evil)";   
                    document.getElementById("i5").innerHTML = "Sincerity. There’s no good in pretending to be something I’m not. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Destiny. Nothing and no one can steer me away from my higher calling. (Any)"; 
                    document.getElementById("b1").innerHTML = "I have a family, but I have no idea where they are. One day, I hope to see them again.";
                    document.getElementById("b2").innerHTML = "I worked the land, I love the land, and I will protect the land.";
                    document.getElementById("b3").innerHTML = "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.";
                    document.getElementById("b4").innerHTML = "My tools are symbols of my past life, and I carry them so that I will never forget my roots.";
                    document.getElementById("b5").innerHTML = "I protect those who cannot protect themselves.";
                    document.getElementById("b6").innerHTML = "I wish my childhood sweetheart had come with me to pursue my destiny.";
                    document.getElementById("f1").innerHTML = "The tyrant who rules my land will stop at nothing to see me killed.";
                    document.getElementById("f2").innerHTML = "I’m convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.";
                    document.getElementById("f3").innerHTML = "The people who knew me when I was young know my shameful secret, so I can never go home again.";
                    document.getElementById("f4").innerHTML = "I have a weakness for the vices of the city, especially hard drink.";
                    document.getElementById("f5").innerHTML = "Secretly, I believe that things would be better if I were a tyrant lording over the land.";
                    document.getElementById("f6").innerHTML = "I have trouble trusting in my allies.";
                    document.getElementById("100").innerHTML = "Select a Defining Event.";
                    document.getElementById("101").innerHTML = "I stood up to a tyrant’s agents.";
                    document.getElementById("102").innerHTML = "I saved people during a natural disaster.";
                    document.getElementById("103").innerHTML = "I stood alone against a terrible monster.";
                    document.getElementById("104").innerHTML = "I stole from a corrupt merchant to help the poor.";
                    document.getElementById("105").innerHTML = "I led a militia to fight off an invading army.";
                    document.getElementById("106").innerHTML = "I broke into a tyrant’s castle and stole weapons to arm the people.";
                    document.getElementById("107").innerHTML = "I trained the peasantry to use farm implements as weapons against a tyrant’s soldiers.";
                    document.getElementById("108").innerHTML = "A lord rescinded an unpopular decree after I led a symbolic act of protect against it.";
                    document.getElementById("109").innerHTML = "A celestial, fey, or similar creature gave me a blessing or revealed my secret origin.";
                    document.getElementById("1010").innerHTML = "Recruited into a lord’s army, I rose to leadership and was commended for my heroism.";    
                    }else if (background === "Guild Artisan") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="visible";    
                    document.getElementById("p1").innerHTML = "I believe that anything worth doing is worth doing right. I can’t help it— I’m a perfectionist.";
                    document.getElementById("p2").innerHTML = "I’m a snob who looks down on those who can’t appreciate fine art.";
                    document.getElementById("p3").innerHTML = "I always want to know how things work and what makes people tick.";
                    document.getElementById("p4").innerHTML = "I’m full of witty aphorisms and have a proverb for every occasion.";
                    document.getElementById("p5").innerHTML = "I’m rude to people who lack my commitment to hard work and fair play.";
                    document.getElementById("p6").innerHTML = "I like to talk at length about my profession.";
                    document.getElementById("p7").innerHTML = "I don’t part with my money easily and will haggle tirelessly to get the best deal possible.";
                    document.getElementById("p8").innerHTML = "I’m well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven’t heard of me.";
                    document.getElementById("i1").innerHTML = "Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)";
                    document.getElementById("i2").innerHTML = "Generosity. My talents were given to me so that I could use them to benefit the world. (Good)";    
                    document.getElementById("i3").innerHTML = "Freedom. Everyone should be free to pursue his or her own livelihood. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Greed. I’m only in it for the money. (Evil)";   
                    document.getElementById("i5").innerHTML = "People. I’m committed to the people I care about, not to ideals. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Aspiration. I work hard to be the best there is at my craft."; 
                    document.getElementById("b1").innerHTML = "The workshop where I learned my trade is the most important place in the world to me.";
                    document.getElementById("b2").innerHTML = "I created a great work for someone, and then found them unworthy to receive it. I’m still looking for someone worthy.";
                    document.getElementById("b3").innerHTML = "I owe my guild a great debt for forging me into the person I am today.";
                    document.getElementById("b4").innerHTML = "I pursue wealth to secure someone’s love.";
                    document.getElementById("b5").innerHTML = "One day I will return to my guild and prove that I am the greatest artisan of them all.";
                    document.getElementById("b6").innerHTML = "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.";
                    document.getElementById("f1").innerHTML = "I’ll do anything to get my hands on something rare or priceless.";
                    document.getElementById("f2").innerHTML = "I’m quick to assume that someone is trying to cheat me.";
                    document.getElementById("f3").innerHTML = "No one must ever learn that I once stole money from guild coffers.";
                    document.getElementById("f4").innerHTML = "I’m never satisfied with what I have— I always want more.";
                    document.getElementById("f5").innerHTML = "I would kill to acquire a noble title.";
                    document.getElementById("f6").innerHTML = "I’m horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I’m surrounded by rivals.";
                    document.getElementById("200").innerHTML = "Select a Guild Business";
                    document.getElementById("201").innerHTML = "Alchemists and apothecaries";
                    document.getElementById("202").innerHTML = "Armorers, locksmiths, and finesmiths";
                    document.getElementById("203").innerHTML = "Brewers, distillers, and vintners";
                    document.getElementById("204").innerHTML = "Calligraphers, scribes, and scriveners";
                    document.getElementById("205").innerHTML = "Carpenters, roofers, and plasterers";
                    document.getElementById("206").innerHTML = "Cartographers, surveyors, and chart-makers";
                    document.getElementById("207").innerHTML = "Cobblers and shoemakers";
                    document.getElementById("208").innerHTML = "Cooks and bakers";
                    document.getElementById("209").innerHTML = "Glassblowers and glaziers";
                    document.getElementById("2010").innerHTML = "Jewelers and gemcutters";    
                    document.getElementById("2011").innerHTML = "Leatherworkers, skinners, and tanners";
                    document.getElementById("2012").innerHTML = "Masons and stonecutters";   
                    document.getElementById("2013").innerHTML = "Painters, limners, and sign-makers";  
                    document.getElementById("2014").innerHTML = "Potters and tile-makers"; 
                    document.getElementById("2015").innerHTML = "Shipwrights and sailmakers";
                    document.getElementById("2016").innerHTML = "Smiths and metal-forgers";
                    document.getElementById("2017").innerHTML = "Tinkers, pewterers, and casters";
                    document.getElementById("2018").innerHTML = "Wagon-makers and wheelwrights";
                    document.getElementById("2019").innerHTML = "Weavers and dyers";
                    document.getElementById("2020").innerHTML = "Woodcarvers, coopers, and bowyers";    
                }else if (background === "Hermit") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="visible";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";    
                    document.getElementById("p1").innerHTML = "I’ve been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.";
                    document.getElementById("p2").innerHTML = "I am utterly serene, even in the face of disaster.";
                    document.getElementById("p3").innerHTML = "The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.";
                    document.getElementById("p4").innerHTML = "I feel tremendous empathy for all who suffer.";
                    document.getElementById("p5").innerHTML = "I’m oblivious to etiquette and social expectations.";
                    document.getElementById("p6").innerHTML = "I connect everything that happens to me to a grand, cosmic plan.";
                    document.getElementById("p7").innerHTML = "I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.";
                    document.getElementById("p8").innerHTML = "I am working on a grand philosophical theory and love sharing my ideas.";
                    document.getElementById("i1").innerHTML = "Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)";
                    document.getElementById("i2").innerHTML = "Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)";   
                    document.getElementById("i5").innerHTML = "Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Self-Knowledge. If you know yourself, there’s nothing left to know. (Any)"; 
                    document.getElementById("b1").innerHTML = "Nothing is more important than the other members of my hermitage, order, or association.";
                    document.getElementById("b2").innerHTML = "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.";
                    document.getElementById("b3").innerHTML = "I’m still seeking the enlightenment I pursued in my seclusion, and it still eludes me.";
                    document.getElementById("b4").innerHTML = "I entered seclusion because I loved someone I could not have.";
                    document.getElementById("b5").innerHTML = "Should my discovery come to light, it could bring ruin to the world.";
                    document.getElementById("b6").innerHTML = "My isolation gave me great insight into a great evil that only I can destroy.";
                    document.getElementById("f1").innerHTML = "Now that I've returned to the world, I enjoy its delights a little too much.";
                    document.getElementById("f2").innerHTML = "I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.";
                    document.getElementById("f3").innerHTML = "I am dogmatic in my thoughts and philosophy.";
                    document.getElementById("f4").innerHTML = "I let my need to win arguments overshadow friendships and harmony.";
                    document.getElementById("f5").innerHTML = "I’d risk too much to uncover a lost bit of knowledge.";
                    document.getElementById("f6").innerHTML = "I like keeping secrets and won’t share them with anyone.";
                    document.getElementById("80").innerHTML = "Select a Life of Seclusion";
                    document.getElementById("81").innerHTML = "I was searching for spiritual enlightenment.";
                    document.getElementById("82").innerHTML = "I was partaking of communal living in accordance with the dictates of a religious order.";
                    document.getElementById("83").innerHTML = "I was exiled for a crime I didn’t commit.";
                    document.getElementById("84").innerHTML = "I retreated from society after a life-altering event.";
                    document.getElementById("85").innerHTML = "I needed a quiet place to work on my art, literature, music, or manifesto.";
                    document.getElementById("86").innerHTML = "I needed to commune with nature, far from civilization.";
                    document.getElementById("87").innerHTML = "I was the caretaker of an ancient ruin or relic.";
                    document.getElementById("88").innerHTML = "I was a pilgrim in search of a person, place, or relic of spiritual significance.";   
                }else if (background === "Noble") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.";
                    document.getElementById("p2").innerHTML = "The common folk love me for my kindness and generosity.";
                    document.getElementById("p3").innerHTML = "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.";
                    document.getElementById("p4").innerHTML = "I take great pains to always look my best and follow the latest fashions.";
                    document.getElementById("p5").innerHTML = "I don’t like to get my hands dirty, and I won’t be caught dead in unsuitable accommodations.";
                    document.getElementById("p6").innerHTML = "Despite my noble birth, I do not place myself above other folk. We all have the same blood.";
                    document.getElementById("p7").innerHTML = "My favor, once lost, is lost forever.";
                    document.getElementById("p8").innerHTML = "If you do me an injury, I will crush you, ruin your name, and salt your fields.";
                    document.getElementById("i1").innerHTML = "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)";
                    document.getElementById("i2").innerHTML = "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Power. If I can attain more power, no one will tell me what to do. (Evil)";   
                    document.getElementById("i5").innerHTML = "Family. Blood runs thicker than water. (Any)";  
                    document.getElementById("i6").innerHTML = "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)"; 
                    document.getElementById("b1").innerHTML = "I will face any challenge to win the approval of my family.";
                    document.getElementById("b2").innerHTML = "My house’s alliance with another noble family must be sustained at all costs.";
                    document.getElementById("b3").innerHTML = "Nothing is more important than the other members of my family.";
                    document.getElementById("b4").innerHTML = "I am in love with the heir of a family that my family despises.";
                    document.getElementById("b5").innerHTML = "My loyalty to my sovereign is unwavering.";
                    document.getElementById("b6").innerHTML = "The common folk must see me as a hero of the people.";
                    document.getElementById("f1").innerHTML = "I secretly believe that everyone is beneath me.";
                    document.getElementById("f2").innerHTML = "I hide a truly scandalous secret that could ruin my family forever.";
                    document.getElementById("f3").innerHTML = "I too often hear veiled insults and threats in every word addressed to me, and I’m quick to anger.";
                    document.getElementById("f4").innerHTML = "I have an insatiable desire for carnal pleasures.";
                    document.getElementById("f5").innerHTML = "In fact, the world does revolve around me.";
                    document.getElementById("f6").innerHTML = "By my words and actions, I often bring shame to my family.";
                }else if (background === "Outlander") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="visible";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I’m driven by a wanderlust that led me away from home.";
                    document.getElementById("p2").innerHTML = "I watch over my friends as if they were a litter of newborn pups.";
                    document.getElementById("p3").innerHTML = "I once ran twenty-five miles without stopping to warn to my clan of an approaching orc horde. I’d do it again if I had to.";
                    document.getElementById("p4").innerHTML = "I have a lesson for every situation, drawn from observing nature.";
                    document.getElementById("p5").innerHTML = "I place no stock in wealthy or well-mannered folk. Money and manners won’t save you from a hungry owlbear.";
                    document.getElementById("p6").innerHTML = "I’m always picking things up, absently fiddling with them, and sometimes accidentally breaking them.";
                    document.getElementById("p7").innerHTML = "I feel far more comfortable around animals than people.";
                    document.getElementById("p8").innerHTML = "I was, in fact, raised by wolves.";
                    document.getElementById("i1").innerHTML = "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)";
                    document.getElementById("i2").innerHTML = "Greater Good. It is each person’s responsibility to make the most happiness for the whole tribe. (Good)";    
                    document.getElementById("i3").innerHTML = "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)";
                    document.getElementById("i4").innerHTML = "Might. The strongest are meant to rule. (Evil)";   
                    document.getElementById("i5").innerHTML = "Nature. The natural world is more important than all the constructs of civilization. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Glory. I must earn glory in battle, for myself and my clan. (Any)"; 
                    document.getElementById("b1").innerHTML = "My family, clan, or tribe is the most important thing in my life, even when they are far from me.";
                    document.getElementById("b2").innerHTML = "An injury to the unspoiled wilderness of my home is an injury to me.";
                    document.getElementById("b3").innerHTML = "I will bring terrible wrath down on the evildoers who destroyed my homeland.";
                    document.getElementById("b4").innerHTML = "I am the last of my tribe, and it is up to me to ensure their names enter legend.";
                    document.getElementById("b5").innerHTML = "I suffer awful visions of a coming disaster and will do anything to prevent it.";
                    document.getElementById("b6").innerHTML = "It is my duty to provide children to sustain my tribe.";
                    document.getElementById("f1").innerHTML = "I am too enamored of ale, wine, and other intoxicants.";
                    document.getElementById("f2").innerHTML = "There’s no room for caution in a life lived to the fullest.";
                    document.getElementById("f3").innerHTML = "I remember every insult I’ve received and nurse a silent resentment toward anyone who’s ever wronged me.";
                    document.getElementById("f4").innerHTML = "I am slow to trust members of other races, tribes, and societies.";
                    document.getElementById("f5").innerHTML = "Violence is my answer to almost any challenge.";
                    document.getElementById("f6").innerHTML = "Don’t expect me to save those who can’t save themselves. It is nature’s way that the strong thrive and the weak perish.";
                    document.getElementById("100").innerHTML = "Please Select an Origin";
                    document.getElementById("101").innerHTML = "Forester";
                    document.getElementById("102").innerHTML = "Trapper";
                    document.getElementById("103").innerHTML = "Homesteader";
                    document.getElementById("104").innerHTML = "Guide";
                    document.getElementById("105").innerHTML = "Exile or outcast";
                    document.getElementById("106").innerHTML = "Bounty hunter";
                    document.getElementById("107").innerHTML = "Pilgrim";
                    document.getElementById("108").innerHTML = "Tribal nomad";
                    document.getElementById("109").innerHTML = "Hunter-gatherer";
                    document.getElementById("1010").innerHTML = "Tribal marauder";
                }else if (background === "Sage") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="visible";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I use polysyllabic words that convey the impression of great erudition.";
                    document.getElementById("p2").innerHTML = "I've read every book in the world’s greatest libraries— or I like to boast that I have.";
                    document.getElementById("p3").innerHTML = "I'm used to helping out those who aren’t as smart as I am, and I patiently explain anything and everything to others.";
                    document.getElementById("p4").innerHTML = "There’s nothing I like more than a good mystery.";
                    document.getElementById("p5").innerHTML = "I’m willing to listen to every side of an argument before I make my own judgment.";
                    document.getElementById("p6").innerHTML = "I . . . speak . . . slowly . . . when talking . . . to idiots, . . . which . . . almost . . . everyone . . . is . . . compared . . . to me.";
                    document.getElementById("p7").innerHTML = "I am horribly, horribly awkward in social situations.";
                    document.getElementById("p8").innerHTML = "I’m convinced that people are always trying to steal my secrets.";
                    document.getElementById("i1").innerHTML = "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)";
                    document.getElementById("i2").innerHTML = "Beauty. What is beautiful points us beyond itself toward what is true. (Good)";    
                    document.getElementById("i3").innerHTML = "Logic. Emotions must not cloud our logical thinking. (Lawful)";
                    document.getElementById("i4").innerHTML = "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)";   
                    document.getElementById("i5").innerHTML = "Power. Knowledge is the path to power and domination. (Evil)";  
                    document.getElementById("i6").innerHTML = "Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)"; 
                    document.getElementById("b1").innerHTML = "It is my duty to protect my students.";
                    document.getElementById("b2").innerHTML = "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.";
                    document.getElementById("b3").innerHTML = "I work to preserve a library, university, scriptorium, or monastery.";
                    document.getElementById("b4").innerHTML = "My life’s work is a series o f tomes related to a specific field of lore.";
                    document.getElementById("b5").innerHTML = "I've been searching my whole life for the answer to a certain question.";
                    document.getElementById("b6").innerHTML = "I sold my soul for knowledge. I hope to do great deeds and win it back.";
                    document.getElementById("f1").innerHTML = "I am easily distracted by the promise of information.";
                    document.getElementById("f2").innerHTML = "Most people scream and run when they see a demon. I stop and take notes on its anatomy.";
                    document.getElementById("f3").innerHTML = "Unlocking an ancient mystery is worth the price of a civilization.";
                    document.getElementById("f4").innerHTML = "I overlook obvious solutions in favor of complicated ones.";
                    document.getElementById("f5").innerHTML = "I speak without really thinking through my words, invariably insulting others.";
                    document.getElementById("f6").innerHTML = "I can’t keep a secret to save my life, or anyone else’s.";
                    document.getElementById("80").innerHTML = "Select a Specialty";
                    document.getElementById("81").innerHTML = "Alchemist";
                    document.getElementById("82").innerHTML = "Astronomer";
                    document.getElementById("83").innerHTML = "Discredited academic";
                    document.getElementById("84").innerHTML = "Librarian";
                    document.getElementById("85").innerHTML = "Professor";
                    document.getElementById("86").innerHTML = "Researcher";
                    document.getElementById("87").innerHTML = "Wizard’s apprentice";
                    document.getElementById("88").innerHTML = "Scribe";
                }else if (background === "Sailor") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "My friends know they can rely on me, no matter what.";
                    document.getElementById("p2").innerHTML = "I work hard so that I can play hard when the work is done.";
                    document.getElementById("p3").innerHTML = "I enjoy sailing into new ports and making new friends over a flagon of ale.";
                    document.getElementById("p4").innerHTML = "I stretch the truth for the sake of a good story.";
                    document.getElementById("p5").innerHTML = "To me, a tavern brawl is a nice way to get to know a new city.";
                    document.getElementById("p6").innerHTML = "I never pass up a friendly wager.";
                    document.getElementById("p7").innerHTML = "My language is as foul as an otyugh nest.";
                    document.getElementById("p8").innerHTML = "I like a job well done, especially if I can convince someone else to do it.";
                    document.getElementById("i1").innerHTML = "Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)";
                    document.getElementById("i2").innerHTML = "Fairness. We all do the work, so we all share in the rewards. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Freedom. The sea is freedom—the freedom to go anywhere and do anything. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Mastery. I’m a predator, and the other ships on the sea are my prey. (Evil)";   
                    document.getElementById("i5").innerHTML = "People. I’m committed to my crewmates, not to ideals. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Aspiration. Someday I’ll own my own ship and chart my own destiny. (Any)"; 
                    document.getElementById("b1").innerHTML = "I’m loyal to my captain first, everything else second.";
                    document.getElementById("b2").innerHTML = "The ship is most important—crewmates and captains come and go.";
                    document.getElementById("b3").innerHTML = "I’ll always remember my first ship.";
                    document.getElementById("b4").innerHTML = "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.";
                    document.getElementById("b5").innerHTML = "I was cheated out of my fair share of the profits, and I want to get my due.";
                    document.getElementById("b6").innerHTML = "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.";
                    document.getElementById("f1").innerHTML = "I follow orders, even if I think they’re wrong.";
                    document.getElementById("f2").innerHTML = "I’ll say anything to avoid having to do extra work.";
                    document.getElementById("f3").innerHTML = "Once someone questions my courage, I never back down no matter how dangerous the situation.";
                    document.getElementById("f4").innerHTML = "Once I start drinking, it’s hard for me to stop.";
                    document.getElementById("f5").innerHTML = "I can’t help but pocket loose coins and other trinkets I come across.";
                    document.getElementById("f6").innerHTML = "My pride will probably lead to my destruction.";
                }else if (background === "Soldier") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="visible";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I'm always polite and respectful.";
                    document.getElementById("p2").innerHTML = "I’m haunted by memories o f war. I can’t get the images of violence out of my mind.";
                    document.getElementById("p3").innerHTML = "I’ve lost too many friends, and I’m slow to make new ones.";
                    document.getElementById("p4").innerHTML = "I’m full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.";
                    document.getElementById("p5").innerHTML = "I can stare down a hell hound without flinching.";
                    document.getElementById("p6").innerHTML = "I enjoy being strong and like breaking things.";
                    document.getElementById("p7").innerHTML = "I have a crude sense of humor.";
                    document.getElementById("p8").innerHTML = "I face problems head-on. A simple, direct solution is the best path to success.";
                    document.getElementById("i1").innerHTML = "Greater Good. Our lot is to lay down our lives in defense of others. (Good)";
                    document.getElementById("i2").innerHTML = "Responsibility. I do what I must and obey just authority. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Might. In life as in war, the stronger force wins. (Evil)";   
                    document.getElementById("i5").innerHTML = "Live and Let Live. Ideals aren’t worth killing over or going to war for. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Nation. My city, nation, or people are all that matter. (Any)"; 
                    document.getElementById("b1").innerHTML = "I would still lay down my life for the people I served with.";
                    document.getElementById("b2").innerHTML = "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.";
                    document.getElementById("b3").innerHTML = "My honor is my life.";
                    document.getElementById("b4").innerHTML = "I’ll never forget the crushing defeat my company suffered or the enemies who dealt it.";
                    document.getElementById("b5").innerHTML = "Those who fight beside me are those worth dying for.";
                    document.getElementById("b6").innerHTML = "I fight for those who cannot fight for themselves.";
                    document.getElementById("f1").innerHTML = "The monstrous enemy we faced in battle still leaves me quivering with fear.";
                    document.getElementById("f2").innerHTML = "I have little respect for anyone who is not a proven warrior.";
                    document.getElementById("f3").innerHTML = "I made a terrible mistake in battle cost many lives— and I would do anything to keep that mistake secret.";
                    document.getElementById("f4").innerHTML = "My hatred of my enemies is blind and unreasoning.";
                    document.getElementById("f5").innerHTML = "I obey the law, even if the law causes misery.";
                    document.getElementById("f6").innerHTML = "I’d rather eat my armor than admit when I’m wrong.";
                    document.getElementById("80").innerHTML = "Select a Specialty";
                    document.getElementById("81").innerHTML = "Officer";
                    document.getElementById("82").innerHTML = "Scout";
                    document.getElementById("83").innerHTML = "Infantry";
                    document.getElementById("84").innerHTML = "Cavalry";
                    document.getElementById("85").innerHTML = "Healer";
                    document.getElementById("86").innerHTML = "Quartermaster";
                    document.getElementById("87").innerHTML = "Standard bearer";
                    document.getElementById("88").innerHTML = "Support staff (cook, blacksmith, or the like)";
                }else if (background === "Urchin") {
                    document.getElementById("bonus6").style.visibility="hidden";
                    document.getElementById("bonus8").style.visibility="hidden";
                    document.getElementById("bonus10").style.visibility="hidden";
                    document.getElementById("bonus20").style.visibility="hidden";
                    document.getElementById("p1").innerHTML = "I hide scraps of food and trinkets away in my pockets.";
                    document.getElementById("p2").innerHTML = "I ask a lot of questions.";
                    document.getElementById("p3").innerHTML = "I like to squeeze into small places where no one else can get to me.";
                    document.getElementById("p4").innerHTML = "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.";
                    document.getElementById("p5").innerHTML = "I eat like a pig and have bad manners.";
                    document.getElementById("p6").innerHTML = "I think anyone who’s nice to me is hiding evil intent.";
                    document.getElementById("p7").innerHTML = "I don’t like to bathe.";
                    document.getElementById("p8").innerHTML = "I bluntly say what other people are hinting at or hiding.";
                    document.getElementById("i1").innerHTML = "Respect. All people, rich or poor, deserve respect. (Good)";
                    document.getElementById("i2").innerHTML = "Community. We have to take care of each other, because no one else is going to do it. (Lawful)";    
                    document.getElementById("i3").innerHTML = "Change. The low are lifted up, and the high and mighty are brought down. Change is the nature o f things. (Chaotic)";
                    document.getElementById("i4").innerHTML = "Retribution. The rich need to be shown what life and death are like in the gutters. (Evil)";   
                    document.getElementById("i5").innerHTML = "People. I help the people who help me—that’s what keeps us alive. (Neutral)";  
                    document.getElementById("i6").innerHTML = "Aspiration. I'm going to prove that I'm worthy of a better life."; 
                    document.getElementById("b1").innerHTML = "My town or city is my home, and I’ll fight to defend it.";
                    document.getElementById("b2").innerHTML = "I sponsor an orphanage to keep others from enduring what I was forced to endure.";
                    document.getElementById("b3").innerHTML = "I owe my survival to another urchin who taught me to live on the streets.";
                    document.getElementById("b4").innerHTML = "I owe a debt I can never repay to the person who took pity on me.";
                    document.getElementById("b5").innerHTML = "I escaped my life of poverty by robbing an important person, and I’m wanted for it.";
                    document.getElementById("b6").innerHTML = "No one else should have to endure the hardships I’ve been through.";
                    document.getElementById("f1").innerHTML = "If I'm outnumbered, I will run away from a fight.";
                    document.getElementById("f2").innerHTML = "Gold seems like a lot of money to me, and I’ll do just about anything for more of it.";
                    document.getElementById("f3").innerHTML = "I will never fully trust anyone other than myself.";
                    document.getElementById("f4").innerHTML = "I’d rather kill someone in their sleep then fight fair.";
                    document.getElementById("f5").innerHTML = "It’s not stealing if I need it more than someone else.";
                    document.getElementById("f6").innerHTML = "People who can't take care of themselves get what they deserve.";
                  
                }else{
                    
                }
                  
             

    
            };            
            
        
           // function bladeward(){
            //       alert("Casting Time: 1 Action\nRange: Self\nDuration: 1 Round\n\nYou extend your hand and trace a sigil of warding in the air. Until the end o f your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.")
              // };
               